package calculadora;

import static constans.Operators.*;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author Lenovo
 */
public class Ventana extends javax.swing.JFrame {

    private Double firts_number;
    private Double second_number;
    private Double resultado;

    private String sFirtsNumber;
    private String sSecondNumber;

    private String operator;
    private boolean finish = false;

    public Ventana() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnNumber7 = new javax.swing.JButton();
        btnNumber8 = new javax.swing.JButton();
        btnNumber9 = new javax.swing.JButton();
        btnNumber4 = new javax.swing.JButton();
        btnNumber5 = new javax.swing.JButton();
        btnNumber6 = new javax.swing.JButton();
        btnNumber1 = new javax.swing.JButton();
        btnNumber2 = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnNumber3 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnNumber0 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtPantalla = new javax.swing.JLabel();
        txtResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNumber7.setText("7");
        btnNumber7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber7ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNumber7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 50));

        btnNumber8.setText("8");
        btnNumber8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber8ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNumber8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 50, 50));

        btnNumber9.setText("9");
        btnNumber9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber9ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNumber9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 50, 50));

        btnNumber4.setText("4");
        btnNumber4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNumber4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 50, 50));

        btnNumber5.setText("5");
        btnNumber5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber5ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNumber5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 50, 50));

        btnNumber6.setText("6");
        btnNumber6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber6ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNumber6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 50, 50));

        btnNumber1.setText("1");
        btnNumber1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 50));

        btnNumber2.setText("2");
        btnNumber2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNumber2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 50, 50));

        btnDiv.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exbtnlight.png"))); // NOI18N
        btnDiv.setText("/");
        btnDiv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });
        jPanel2.add(btnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 50, 50));

        btnNumber3.setText("3");
        btnNumber3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNumber3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 50, 50));

        btnPunto.setText(".");
        btnPunto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        jPanel2.add(btnPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 50, 50));

        btnNumber0.setText("0");
        btnNumber0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumber0ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNumber0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, 50));

        jButton3.setText("<-");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 50, 50));

        btnFactorial.setText("!");
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });
        jPanel2.add(btnFactorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 50, 50));

        btnX.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exbtnlight.png"))); // NOI18N
        btnX.setText("*");
        btnX.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });
        jPanel2.add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 50, 50));

        btnMinus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exbtnlight.png"))); // NOI18N
        btnMinus.setText("-");
        btnMinus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });
        jPanel2.add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 50, 50));

        btnPlus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exbtnlight.png"))); // NOI18N
        btnPlus.setText("+");
        btnPlus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });
        jPanel2.add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 50, 50));

        btnEquals.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEquals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exbtnlight.png"))); // NOI18N
        btnEquals.setText("=");
        btnEquals.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });
        jPanel2.add(btnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 50, 50));

        jButton1.setText("C");
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 50));

        jButton5.setText("%");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 50, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 300, 320));

        txtPantalla.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtPantalla.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel1.add(txtPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 40));

        txtResult.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        txtResult.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtResult.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(txtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber1ActionPerformed
        addNumber("1");
    }//GEN-LAST:event_btnNumber1ActionPerformed

    private void btnNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber2ActionPerformed
        addNumber("2");
    }//GEN-LAST:event_btnNumber2ActionPerformed

    private void btnNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber3ActionPerformed
        addNumber("3");
    }//GEN-LAST:event_btnNumber3ActionPerformed

    private void btnNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber4ActionPerformed
        addNumber("4");
    }//GEN-LAST:event_btnNumber4ActionPerformed

    private void btnNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber5ActionPerformed
        addNumber("5");
    }//GEN-LAST:event_btnNumber5ActionPerformed

    private void btnNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber6ActionPerformed
        addNumber("6");
    }//GEN-LAST:event_btnNumber6ActionPerformed

    private void btnNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber7ActionPerformed
        addNumber("7");
    }//GEN-LAST:event_btnNumber7ActionPerformed

    private void btnNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber8ActionPerformed
        addNumber("8");
    }//GEN-LAST:event_btnNumber8ActionPerformed

    private void btnNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber9ActionPerformed
        addNumber("9");
    }//GEN-LAST:event_btnNumber9ActionPerformed

    private void btnNumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumber0ActionPerformed
        addNumber("0");
    }//GEN-LAST:event_btnNumber0ActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        operationBtn(ADDITION);
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        operationBtn(SUBTRACTION);
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        operationBtn(MULTIPLICATION);
    }//GEN-LAST:event_btnXActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        if (sFirtsNumber == null) {
            return;
        }
        if (sSecondNumber == null && sFirtsNumber != null) {
            if (operator != null) {
                //Poner sonido
                return;
            }
            txtResult.setText(sFirtsNumber);
            return;
        }
        operar();
        txtResult.setText(formatNumber(resultado));
        finish = true;
    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        addPoint();
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearSystems();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        remove();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        operationBtn(DIVISION);
    }//GEN-LAST:event_btnDivActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (sFirtsNumber != null) {
            Double number = Double.valueOf(sFirtsNumber);
            Double result = number / 100;
            if (operator != null) {
                String exp = firts_number + operator + result;
                txtPantalla.setText(exp);
                return;
            }
            txtResult.setText(formatNumber(result));
            finish = true;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        if (sFirtsNumber != null) {
            Double number = Double.valueOf(sFirtsNumber);
            Double result = calculateFactorial(number);
            if (operator != null) {
                number = Double.valueOf(sSecondNumber);
                result = calculateFactorial(number);
                String exp = firts_number + operator + result;
                txtPantalla.setText(exp);
                return;
            }
            txtResult.setText(formatNumber(result));
            finish = true;
        }
    }//GEN-LAST:event_btnFactorialActionPerformed

    private void operar() {
        second_number = Double.valueOf(sSecondNumber);
        Double result;
        switch (operator) {
            case ADDITION:
                result = firts_number + second_number;
                break;
            case SUBTRACTION:
                result = firts_number - second_number;
                break;
            case MULTIPLICATION:
                result = firts_number * second_number;
                break;
            case DIVISION:
                if (second_number == 0.0) {
                    result = Double.NaN;
                    break;
                }
                result = firts_number / second_number;
                break;
            default:
                throw new AssertionError();
        }
        operator = null;
        firts_number = result;
        sFirtsNumber = firts_number.toString();
        resultado = result;
    }

    private void operationBtn(String op) {
        if (sFirtsNumber == null) {
            return;
        }
        firts_number = Double.valueOf(sFirtsNumber);
        finish = false;
        if (operator != null) {
            operar();
        }
        addNumberAux(op);
        operator = op;
    }

    private void addNumber(String n) {
        if (finish) {
            clearSystems();
            finish = false;
        }
        txtPantalla.setText(txtPantalla.getText() + n);
        if (operator == null) {
            sFirtsNumber = txtPantalla.getText();
        } else {
            addSecondNumber();
        }
    }

    private void addSecondNumber() {
        String exp = txtPantalla.getText();
        int i = exp.lastIndexOf(operator) + 1;
        sSecondNumber = txtPantalla.getText().substring(i, exp.length());
    }

    private void addPoint() {
        if (txtPantalla.getText().isEmpty() || finish) {
            //Poner sonido de inhabilitado
            return;
        }
        addNumberAux(".");
    }

    private void addNumberAux(String n) {
        txtPantalla.setText(txtPantalla.getText() + n);
    }

    private void clearSystems() {
        clearSystemAux();
        txtResult.setText("");
        firts_number = null;
        second_number = null;
        sFirtsNumber = null;
        sSecondNumber = null;
    }

    private void clearSystemAux() {
        txtPantalla.setText("");
    }

    private String formatNumber(Double n) {
        if (n % 1 == 0) {
            return n.intValue() + "";
        }
        return n.toString();
    }

    private void remove() {
        String exp = txtPantalla.getText();
        if (finish) {
            clearSystems();
            finish = false;
            return;
        }
        if (exp.length() > 0 || operator != null) {
            if (sSecondNumber != null && sSecondNumber.length() > 0 && operator != null) {
                sSecondNumber = sSecondNumber.substring(0, sSecondNumber.length() - 1);
            }
            if (sFirtsNumber != null && sFirtsNumber.length() > 0 && operator == null) {
                sFirtsNumber = sFirtsNumber.substring(0, sFirtsNumber.length() - 1);
            }
            if (exp.endsWith(ADDITION)
                    || exp.endsWith(SUBTRACTION)
                    || exp.endsWith(MULTIPLICATION)
                    || exp.endsWith(DIVISION)) {
                operator = null;
            }
            exp = exp.substring(0, exp.length() - 1);
            txtPantalla.setText(exp);
        }
        //Sino poner sonido de boton inhabilitado
    }

    private Double calculateFactorial(Double n) {
        Double factorial = 1.0;
        for (int i = 1; i <= n; i++) {
            factorial *= i;
        }
        return factorial;
    }

    private void sound() {
        Clip clip = null;
        try {
            AudioInputStream ais = AudioSystem.getAudioInputStream(new File("sonido.wav"));
            clip = AudioSystem.getClip();
            clip.open(ais);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            System.err.println("Error -> " + e.getMessage());
        }
        if (clip != null) {
            clip.start();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnNumber0;
    private javax.swing.JButton btnNumber1;
    private javax.swing.JButton btnNumber2;
    private javax.swing.JButton btnNumber3;
    private javax.swing.JButton btnNumber4;
    private javax.swing.JButton btnNumber5;
    private javax.swing.JButton btnNumber6;
    private javax.swing.JButton btnNumber7;
    private javax.swing.JButton btnNumber8;
    private javax.swing.JButton btnNumber9;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnX;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtPantalla;
    private javax.swing.JLabel txtResult;
    // End of variables declaration//GEN-END:variables
}
